Repository wecode-bootcamp-korea/20-2nd-tteokbokcom-frontend, pull requests merged in 2021-06, with the labels that each got.

#14 [20기 임유진] Modify : conflict 해결, key value 수정
  public/data/ProjectStart/ProjectStartData.json
  src/Routes.js
  src/config.js
  src/pages/ProjectStart/Components/CardHandleBtn.js
  src/pages/ProjectStart/Components/CardItem.js
  src/pages/ProjectStart/Components/ItemContents/AddReward.js
  src/pages/ProjectStart/Components/ItemContents/CreatorIntroduce.js
  src/pages/ProjectStart/Components/ItemContents/CreatorName.js
  src/pages/ProjectStart/Components/ItemContents/GoalAmount.js
  src/pages/ProjectStart/Components/ItemContents/ImgUploader.js
  src/pages/ProjectStart/Components/ItemContents/ProjectCategory.js
  src/pages/ProjectStart/Components/ItemContents/ProjectHandleDate.js
  src/pages/ProjectStart/Components/ItemContents/ProjectSummary.js
  src/pages/ProjectStart/Components/ItemContents/ProjectTag.js
  src/pages/ProjectStart/Components/ItemContents/ProjectTitle.js
  src/pages/ProjectStart/Components/ProjectStartCard.js
  src/pages/ProjectStart/ProjectStart.js
  src/pages/ProjectStart/data/projectStartData.js
Labels: Status: 수정 요청

#22 [20기 임유진] Modify : 등록페이지 탭 전환시 카드 열림 수정, Add : 폼 등록 유저 정보 받아오기 추가
  src/pages/ProjectStart/Components/ItemContents/CreatorIntroduce.js
  src/pages/ProjectStart/Components/ItemContents/CreatorName.js
  src/pages/ProjectStart/ProjectStart.js
Labels: Status: 리뷰 요청

#21 [20기 노선경] Add : User page
  public/data/User/likeData.json
  src/Routes.js
  src/components/Nav/Nav.js
  src/pages/User/Components/Filter.js
  src/pages/User/Components/ProjectCard.js
  src/pages/User/User.js
Labels: Status: Accepted

#24 [20기 임유진] Modify : 메인 페이지 백엔드 통신 후 수정
  src/components/ProjectCard/ProjectCard.js
  src/config.js
  src/pages/Main/Components/ProjectCards.js
Labels: Status: 리뷰 요청

#25 [20기 임유진] Modify : 등록페이지 탭 수정
  src/pages/ProjectStart/Components/ItemContents/ImgUploader.js
  src/pages/ProjectStart/Components/ItemContents/ProjectTag.js
  src/pages/ProjectStart/ProjectStart.js
Labels: Status: 리뷰 요청

#26 [20기 임유진] Modify : 등록페이지 jpg만 업로드 가능하게 수정
  src/config.js
  src/pages/ProjectStart/Components/ItemContents/ImgUploader.js
  src/pages/ProjectStart/ProjectStart.js
  src/pages/ProjectStart/data/projectStartData.js
Labels: Status: 리뷰 요청

#27 [20기 임유진] Modify : 메인페이지 dday 음수 수정, 레이아웃 수정
  src/components/ProjectCard/ProjectCard.js
Labels: Status: 리뷰 요청

#28 [20기 임유진] Modify : 등록페이지 수정
  src/pages/ProjectStart/Components/CardHandleBtn.js
  src/pages/ProjectStart/Components/ItemContents/ProjectHandleDate.js
  src/pages/ProjectStart/Components/ProjectStartCard.js
  src/pages/ProjectStart/ProjectStart.js
  src/utils/checkValid.js
Labels: Status: 리뷰 요청

#31 [20기 임유진] Add : 메인페이지/유저페이지 좋아요 버튼 토글
  src/components/Nav/Nav.js
  src/components/ProjectCard/ProjectCard.js
  src/pages/Detail/Detail.js
  src/pages/Detail/RewardCard.js
  src/pages/Main/Components/ProjectCards.js
  src/pages/ProjectStart/ProjectStart.js
Labels: Status: Accepted

#32 [20기 송가람] Fixed: eslint 에러
  src/pages/Detail/DetailIntroduction.js
  src/pages/Detail/RewardCard.js
Labels: Status: 리뷰 요청

#23 [20기 노선경] Add : 쿼리 생성에 따른 페이지 이동 및 data fetch
  public/index.html
  src/Routes.js
  src/components/AccountContainer/components/Container.js
  src/components/AccountContainer/components/Footer.js
  src/components/Nav/Nav.js
  src/components/ProjectCard/ProjectCard.js
  src/pages/Detail/RewardCard.js
  src/pages/Main/Components/FilterNav.js
  src/pages/Main/Components/FilterWidjet.js
  src/pages/Main/Components/ProjectCards.js
  src/pages/Main/Main.js
  src/pages/User/User.js
Labels: Status: 수정 요청

#33 [20기 임유진] Fix : 등록페이지 introduction 불러오기 버그 수정
  src/pages/ProjectStart/ProjectStart.js
Labels: Status: 리뷰 요청

#36 [20기 임유진] Fix : 등록페이지 수정
  src/pages/Main/Components/ProjectCards.js
  src/pages/ProjectStart/ProjectStart.js
Labels: Status: 리뷰 요청

#35 Modify: Modify profile path
  src/pages/Detail/RewardCard.js
Labels: Status: 리뷰 요청

#34 [20기 노선경] Modify : 레이아웃 수정
  src/components/AccountContainer/components/Footer.js
  src/pages/Detail/DetailProduct.js
  src/pages/Main/Components/FilterWidjet.js
  src/pages/Main/Components/ProjectCards.js
  src/pages/User/User.js
Labels: Status: 리뷰 요청

#41 [20기 임유진] Modify : 확인된 자잘한 문제들 수정
  src/components/Nav/Nav.js
  src/components/ProjectCard/ProjectCard.js
  src/config.js
  src/pages/Detail/Detail.js
  src/pages/Detail/DetailIntroduction.js
  src/pages/Detail/RewardCard.js
  src/pages/Main/Components/ProjectCards.js
  src/pages/ProjectStart/Components/CardHandleBtn.js
  src/pages/ProjectStart/ProjectStart.js
  src/pages/User/User.js
Labels: Status: 리뷰 요청

#42 [20기 임유진] fix garams util route
  src/pages/Detail/Detail.js
  src/utils/validator.js
Labels: Status: 리뷰 요청

#43 [20기 임유진] Fix : user page routing, detail page reward title
  src/pages/Detail/RewardCard.js
  src/pages/Detail/RewardContents.js
  src/pages/User/User.js
Labels: Status: 리뷰 요청
